#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset


python manage.py migrate
{%- if cookiecutter.use_async == 'y' %}
uvicorn config.asgi:application --host 0.0.0.0 --reload
{%- elif cookiecutter.use_vs_code == 'y' %}
python manage.py runserver --enable-debugger 0.0.0.0:8000
{%- else %}
python manage.py runserver_plus 0.0.0.0:8000
{%- endif %}
